# Generated by Django 3.2.21 on 2023-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='receiver',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='sender',
            new_name='sender_user',
        ),
    ]
