# Generated by Django 3.2.21 on 2023-10-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_auto_20231003_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_pictures'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
