# Generated by Django 3.2.21 on 2023-10-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0015_auto_20231004_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
